/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jobportal.jobportal.Views;

import com.jobportal.jobportal.Api.modules.Requests.Auth.LoginRequest;
import com.jobportal.jobportal.Api.modules.Responses.Auth.LoginResponse;
import com.jobportal.jobportal.Api.modules.Auth;
import com.jobportal.jobportal.Api.modules.TokenFile;

import java.io.IOException;
import org.json.JSONException;
import org.apache.http.HttpException;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import com.jobportal.jobportal.SnowBackground;

/**
 *
 * @author kotorkovsciy
 */
public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    
    public Login() {
        SnowBackground snowBackground = new SnowBackground();
        setContentPane(snowBackground);
        initComponents();
        ImageIcon image = new ImageIcon("assets/logo.jpg");
        setIconImage(image.getImage());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLoginForm = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        titleLogin = new javax.swing.JLabel();
        titlePassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Авторизация");
        setResizable(false);

        titleLoginForm.setForeground(new java.awt.Color(255, 255, 255));
        titleLoginForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLoginForm.setText("Авторизация");
        titleLoginForm.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        titleLoginForm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        titleLogin.setForeground(new java.awt.Color(255, 255, 255));
        titleLogin.setText("Логин");

        titlePassword.setForeground(new java.awt.Color(255, 255, 255));
        titlePassword.setText("Пароль");

        btnLogin.setText("Войти");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLogin)
                    .addComponent(titlePassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(login))
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLoginForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(185, 185, 185))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titleLoginForm)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLogin))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titlePassword))
                .addGap(36, 36, 36)
                .addComponent(btnLogin)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        try{
            LoginRequest loginAuth = new LoginRequest(
                login.getText(),
                password.getText()
            );
            LoginResponse response =  Auth.login(loginAuth);
            TokenFile token = new TokenFile();
            
            token.writeToken(response.authToken);
            
            this.dispose();
            Vacancies vacanciesFrame = new Vacancies();
            vacanciesFrame.setVisible(true);
            
        } catch (JSONException e){
            JOptionPane.showMessageDialog(rootPane, e);
        } catch (IOException  e){
            JOptionPane.showMessageDialog(rootPane, e);
        } catch (HttpException e){
            JOptionPane.showMessageDialog(rootPane, "Неверный логин или пароль!");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JTextField login;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel titleLogin;
    private javax.swing.JLabel titleLoginForm;
    private javax.swing.JLabel titlePassword;
    // End of variables declaration//GEN-END:variables
}
