/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jobportal.jobportal.Views;

import javax.swing.JFrame;
import com.jobportal.jobportal.Api.modules.Requests.Vacancy.VacancyResponseRequests;
import com.jobportal.jobportal.Api.modules.Responses.Vacancy.VacancyResponseResponse;
import com.jobportal.jobportal.Api.modules.TokenFile;
import com.jobportal.jobportal.Api.modules.Vacancy;
import com.jobportal.jobportal.SnowBackground;
import java.io.IOException;
import java.net.URISyntaxException;
import javax.swing.ImageIcon;
import org.apache.http.HttpException;
import org.json.JSONException;

/**
 *
 * @author kotorkovsciy
 */
public class VacancyResponse extends javax.swing.JFrame {

    /**
     * Creates new form VacancyResponse
     */
    public VacancyResponse(Integer id) {
        SnowBackground snowBackground = new SnowBackground();
        setContentPane(snowBackground);
        initComponents();
        ImageIcon image = new ImageIcon("assets/logo.jpg");
        setIconImage(image.getImage());
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
        VacancyResponseRequests request = new VacancyResponseRequests(id);
        
        try {
            TokenFile token = new TokenFile();
            VacancyResponseResponse vacancyResponse = Vacancy.getResponse(request, token.readToken());
            
            title.setText(vacancyResponse.title);
            firstName.setText(vacancyResponse.firstName);
            lastName.setText(vacancyResponse.lastName);
            age.setText(vacancyResponse.age.toString());
            salary.setText(vacancyResponse.salary.toString() + " руб.");
            phoneNumber.setText(vacancyResponse.phoneNumber);
            description.setText(vacancyResponse.description);
          
        } catch (IOException | JSONException | HttpException | URISyntaxException e) {
            e.printStackTrace(); // Обработка ошибок
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        salary = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setText("title");

        firstName.setText("first_name");

        lastName.setText("last_name");

        age.setText("age");

        salary.setText("salary");

        phoneNumber.setText("phone number");

        description.setColumns(20);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lastName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(firstName)
                                .addGap(39, 39, 39)
                                .addComponent(age))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(salary)
                        .addGap(40, 40, 40)
                        .addComponent(phoneNumber)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastName)
                    .addComponent(firstName)
                    .addComponent(age))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salary)
                    .addComponent(phoneNumber))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel firstName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastName;
    private javax.swing.JLabel phoneNumber;
    private javax.swing.JLabel salary;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
